# Generated by Django 4.0.6 on 2022-07-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=5, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=27, null=True)),
                ('body', models.CharField(max_length=96, null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.projectcategory')),
            ],
            options={
                'ordering': ['published'],
            },
        ),
    ]
