# Generated by Django 4.0.6 on 2022-07-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
