# Generated by Django 4.0.6 on 2022-07-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_photofor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photofor',
            name='name',
        ),
    ]
