# Generated by Django 4.0.6 on 2022-07-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_getinfo_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
