# Generated by Django 4.0.6 on 2022-07-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_getinfo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getinfo',
            name='date',
        ),
    ]
